name: rlog

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build
      run: ./build.sh
    - name: zip bin directory
      run: | 
        cd build
        sudo tar -czf bin.tar.gz bin
    - name: Upload bin.tar.gz to release
      if: github.ref == 'refs/heads/rlog-release' && github.event_name == 'push'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/bin.tar.gz
        asset_name: bin.tar.gz
        tag: "latest" 
        overwrite: true

